version: '3.8'

services:
  # Service ChromaDB
  chromadb:
    build:
      context: ./vector_db
      dockerfile: Dockerfile.chroma
    container_name: swarmshift-chromadb
    ports:
      - "${CHROMA_SERVER_HTTP_PORT:-8000}:8000"
    entrypoint: chroma
    command: ["run", "./config.yaml"]
    #volumes:
      #- chroma_data:/chroma/chroma
      #- ./chroma_config.yaml:./config.yaml
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_DATA_PATH=/data
    networks:
      - swarmshift-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend FastAPI 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: swarmshift-backend
    ports:
      - "8002:8002"
    volumes:
      # Volume pour les données utilisateur en mode développement
      - ./dev_data:/app/dev_data
      # Volume pour les uploads temporaires
      - uploads_data:/app/uploads
      # Volume pour les données ChromaDB locales
      - chroma_local_data:/app/chroma_db
    environment:
      - ENVIRONMENT=DEV
      - PYTHONPATH=/app
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
      - PORT=8002
      - HOST=0.0.0.0
      - DEV_MODE=true
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - swarmshift-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: swarmshift-frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)

    environment:
      - VITE_API_BASE_URL=http://localhost:8002/api/
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - swarmshift-network
    restart: unless-stopped

# Réseaux
networks:
  swarmshift-network:
    driver: bridge

# Volumes persistants
volumes:
  chroma_data:
    driver: local
  chroma_local_data:
    driver: local
  uploads_data:
    driver: local

